settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: go-admin
  path: .
  commands:
    install:
      status: true
      method: go install
    run:
      status: true
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
