version: "3.9"
services:
  admin-back:
    build: .
    ports:
      - 8000:3000
    image: admin-back
    environment:
      # access these from .env
      - DB_HOST=$DB_HOST 
      - DB_PORT=3306
      - DB_DATABASE=$DB_DATABASE
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - SECRET_KEY=$SECRET_KEY
    extra_hosts:
      # this is required for connecting to the MySQL server on the host
      - "host.docker.internal:host-gateway"    
